<?php

namespace Database\Seeders;

use App\Enum\AppConstant;
use App\Enum\AuthConstant;
use App\Enum\PermissionEnum;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $arrPermission = [
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_SAN_PHAM->description(),
                'PARENT_CODE' => null,
                'TREE_LEVEL' => 1,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_SAN_PHAM->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_DANH_SACH->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_DANH_SACH->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_DANH_SACH->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_CHI_TIET->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_CHI_TIET->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_CHI_TIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_THEM_MOI->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_THEM_MOI->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_THEM_MOI->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_CHINH_SUA->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_CHINH_SUA->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_CHINH_SUA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_XOA->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_XOA->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_SAN_PHAM->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_SAN_PHAM_XOA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'CODE' => PermissionEnum::QL_SAN_PHAM->value,
                'NAME' => PermissionEnum::QL_SAN_PHAM->description(),
                'PARENT_CODE' => null,
                'TREE_LEVEL' => 1,
                'DESCRIPTION' => PermissionEnum::QL_SAN_PHAM->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_SAN_PHAM_DANH_SACH->value,
                'NAME' => PermissionEnum::QL_SAN_PHAM_DANH_SACH->description(),
                'PARENT_CODE' => PermissionEnum::QL_SAN_PHAM->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_SAN_PHAM_DANH_SACH->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_SAN_PHAM_CHI_TIET->value,
                'NAME' => PermissionEnum::QL_SAN_PHAM_CHI_TIET->description(),
                'PARENT_CODE' => PermissionEnum::QL_SAN_PHAM->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_SAN_PHAM_CHI_TIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_SAN_PHAM_THEM_MOI->value,
                'NAME' => PermissionEnum::QL_SAN_PHAM_THEM_MOI->description(),
                'PARENT_CODE' => PermissionEnum::QL_SAN_PHAM->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_SAN_PHAM_THEM_MOI->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_SAN_PHAM_CHINH_SUA->value,
                'NAME' => PermissionEnum::QL_SAN_PHAM_CHINH_SUA->description(),
                'PARENT_CODE' => PermissionEnum::QL_SAN_PHAM->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_SAN_PHAM_CHINH_SUA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_SAN_PHAM_XOA->value,
                'NAME' => PermissionEnum::QL_SAN_PHAM_XOA->description(),
                'PARENT_CODE' => PermissionEnum::QL_SAN_PHAM->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_SAN_PHAM_XOA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'CODE' => PermissionEnum::QL_TIN_TUC->value,
                'NAME' => PermissionEnum::QL_TIN_TUC->description(),
                'PARENT_CODE' => null,
                'TREE_LEVEL' => 1,
                'DESCRIPTION' => PermissionEnum::QL_TIN_TUC->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_TIN_TUC_DANH_SACH->value,
                'NAME' => PermissionEnum::QL_TIN_TUC_DANH_SACH->description(),
                'PARENT_CODE' => PermissionEnum::QL_TIN_TUC->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_TIN_TUC_DANH_SACH->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_TIN_TUC_CHI_TIET->value,
                'NAME' => PermissionEnum::QL_TIN_TUC_CHI_TIET->description(),
                'PARENT_CODE' => PermissionEnum::QL_TIN_TUC->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_TIN_TUC_CHI_TIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_TIN_TUC_THEM_MOI->value,
                'NAME' => PermissionEnum::QL_TIN_TUC_THEM_MOI->description(),
                'PARENT_CODE' => PermissionEnum::QL_TIN_TUC->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_TIN_TUC_THEM_MOI->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_TIN_TUC_CHINH_SUA->value,
                'NAME' => PermissionEnum::QL_TIN_TUC_CHINH_SUA->description(),
                'PARENT_CODE' => PermissionEnum::QL_TIN_TUC->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_TIN_TUC_CHINH_SUA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_TIN_TUC_XOA->value,
                'NAME' => PermissionEnum::QL_TIN_TUC_XOA->description(),
                'PARENT_CODE' => PermissionEnum::QL_TIN_TUC->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_TIN_TUC_XOA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_TIN_TUC->description(),
                'PARENT_CODE' => null,
                'TREE_LEVEL' => 1,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_TIN_TUC->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC_DANH_SACH->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_TIN_TUC_DANH_SACH->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_TIN_TUC_DANH_SACH->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC_CHI_TIET->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_TIN_TUC_CHI_TIET->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_TIN_TUC_CHI_TIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC_THEM_MOI->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_TIN_TUC_THEM_MOI->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_TIN_TUC_THEM_MOI->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC_CHINH_SUA->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_TIN_TUC_CHINH_SUA->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_TIN_TUC_CHINH_SUA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC_XOA->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_TIN_TUC_XOA->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_TIN_TUC->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_TIN_TUC_XOA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_BAI_VIET->description(),
                'PARENT_CODE' => null,
                'TREE_LEVEL' => 1,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_BAI_VIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET_DANH_SACH->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_BAI_VIET_DANH_SACH->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_BAI_VIET_DANH_SACH->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET_CHI_TIET->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_BAI_VIET_CHI_TIET->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_BAI_VIET_CHI_TIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET_THEM_MOI->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_BAI_VIET_THEM_MOI->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_BAI_VIET_THEM_MOI->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET_CHINH_SUA->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_BAI_VIET_CHINH_SUA->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_BAI_VIET_CHINH_SUA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET_XOA->value,
                'NAME' => PermissionEnum::QL_DANH_MUC_BAI_VIET_XOA->description(),
                'PARENT_CODE' => PermissionEnum::QL_DANH_MUC_BAI_VIET->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_DANH_MUC_BAI_VIET_XOA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'CODE' => PermissionEnum::QL_BAI_VIET->value,
                'NAME' => PermissionEnum::QL_BAI_VIET->description(),
                'PARENT_CODE' => null,
                'TREE_LEVEL' => 1,
                'DESCRIPTION' => PermissionEnum::QL_BAI_VIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_BAI_VIET_DANH_SACH->value,
                'NAME' => PermissionEnum::QL_BAI_VIET_DANH_SACH->description(),
                'PARENT_CODE' => PermissionEnum::QL_BAI_VIET->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_BAI_VIET_DANH_SACH->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_BAI_VIET_CHI_TIET->value,
                'NAME' => PermissionEnum::QL_BAI_VIET_CHI_TIET->description(),
                'PARENT_CODE' => PermissionEnum::QL_BAI_VIET->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_BAI_VIET_CHI_TIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_BAI_VIET_THEM_MOI->value,
                'NAME' => PermissionEnum::QL_BAI_VIET_THEM_MOI->description(),
                'PARENT_CODE' => PermissionEnum::QL_BAI_VIET->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_BAI_VIET_THEM_MOI->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_BAI_VIET_CHINH_SUA->value,
                'NAME' => PermissionEnum::QL_BAI_VIET_CHINH_SUA->description(),
                'PARENT_CODE' => PermissionEnum::QL_BAI_VIET->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_BAI_VIET_CHINH_SUA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_BAI_VIET_XOA->value,
                'NAME' => PermissionEnum::QL_BAI_VIET_XOA->description(),
                'PARENT_CODE' => PermissionEnum::QL_BAI_VIET->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_BAI_VIET_XOA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'CODE' => PermissionEnum::QL_VIDEO->value,
                'NAME' => PermissionEnum::QL_VIDEO->description(),
                'PARENT_CODE' => null,
                'TREE_LEVEL' => 1,
                'DESCRIPTION' => PermissionEnum::QL_VIDEO->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_VIDEO_DANH_SACH->value,
                'NAME' => PermissionEnum::QL_VIDEO_DANH_SACH->description(),
                'PARENT_CODE' => PermissionEnum::QL_VIDEO->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_VIDEO_DANH_SACH->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_VIDEO_CHI_TIET->value,
                'NAME' => PermissionEnum::QL_VIDEO_CHI_TIET->description(),
                'PARENT_CODE' => PermissionEnum::QL_VIDEO->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_VIDEO_CHI_TIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_VIDEO_THEM_MOI->value,
                'NAME' => PermissionEnum::QL_VIDEO_THEM_MOI->description(),
                'PARENT_CODE' => PermissionEnum::QL_VIDEO->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_VIDEO_THEM_MOI->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_VIDEO_CHINH_SUA->value,
                'NAME' => PermissionEnum::QL_VIDEO_CHINH_SUA->description(),
                'PARENT_CODE' => PermissionEnum::QL_VIDEO->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_VIDEO_CHINH_SUA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_VIDEO_XOA->value,
                'NAME' => PermissionEnum::QL_VIDEO_XOA->description(),
                'PARENT_CODE' => PermissionEnum::QL_VIDEO->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_VIDEO_XOA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_VIDEO_XEM->value,
                'NAME' => PermissionEnum::QL_VIDEO_XEM->description(),
                'PARENT_CODE' => PermissionEnum::QL_VIDEO->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_VIDEO_XEM->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'CODE' => PermissionEnum::QL_THONG_TIN_CA_NHAN->value,
                'NAME' => PermissionEnum::QL_THONG_TIN_CA_NHAN->description(),
                'PARENT_CODE' => null,
                'TREE_LEVEL' => 1,
                'DESCRIPTION' => PermissionEnum::QL_THONG_TIN_CA_NHAN->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_THONG_TIN_CA_NHAN_CHI_TIET->value,
                'NAME' => PermissionEnum::QL_THONG_TIN_CA_NHAN_CHI_TIET->description(),
                'PARENT_CODE' => PermissionEnum::QL_THONG_TIN_CA_NHAN->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_THONG_TIN_CA_NHAN_CHI_TIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_THONG_TIN_CA_NHAN_CHINH_SUA->value,
                'NAME' => PermissionEnum::QL_THONG_TIN_CA_NHAN_CHINH_SUA->description(),
                'PARENT_CODE' => PermissionEnum::QL_THONG_TIN_CA_NHAN->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_THONG_TIN_CA_NHAN_CHINH_SUA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'CODE' => PermissionEnum::QL_NGUOI_DUNG->value,
                'NAME' => PermissionEnum::QL_NGUOI_DUNG->description(),
                'PARENT_CODE' => null,
                'TREE_LEVEL' => 1,
                'DESCRIPTION' => PermissionEnum::QL_NGUOI_DUNG->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_NGUOI_DUNG_DANH_SACH->value,
                'NAME' => PermissionEnum::QL_NGUOI_DUNG_DANH_SACH->description(),
                'PARENT_CODE' => PermissionEnum::QL_NGUOI_DUNG->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_NGUOI_DUNG_DANH_SACH->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_NGUOI_DUNG_CHI_TIET->value,
                'NAME' => PermissionEnum::QL_NGUOI_DUNG_CHI_TIET->description(),
                'PARENT_CODE' => PermissionEnum::QL_NGUOI_DUNG->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_NGUOI_DUNG_CHI_TIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_NGUOI_DUNG_THEM_MOI->value,
                'NAME' => PermissionEnum::QL_NGUOI_DUNG_THEM_MOI->description(),
                'PARENT_CODE' => PermissionEnum::QL_NGUOI_DUNG->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_NGUOI_DUNG_THEM_MOI->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_NGUOI_DUNG_CHINH_SUA->value,
                'NAME' => PermissionEnum::QL_NGUOI_DUNG_CHINH_SUA->description(),
                'PARENT_CODE' => PermissionEnum::QL_NGUOI_DUNG->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_NGUOI_DUNG_CHINH_SUA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_NGUOI_DUNG_XOA->value,
                'NAME' => PermissionEnum::QL_NGUOI_DUNG_XOA->description(),
                'PARENT_CODE' => PermissionEnum::QL_NGUOI_DUNG->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_NGUOI_DUNG_XOA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'CODE' => PermissionEnum::QL_CAI_DAT->value,
                'NAME' => PermissionEnum::QL_CAI_DAT->description(),
                'PARENT_CODE' => null,
                'TREE_LEVEL' => 1,
                'DESCRIPTION' => PermissionEnum::QL_CAI_DAT->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_CAI_DAT_DANH_SACH->value,
                'NAME' => PermissionEnum::QL_CAI_DAT_DANH_SACH->description(),
                'PARENT_CODE' => PermissionEnum::QL_CAI_DAT->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_CAI_DAT_DANH_SACH->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_CAI_DAT_CHI_TIET->value,
                'NAME' => PermissionEnum::QL_CAI_DAT_CHI_TIET->description(),
                'PARENT_CODE' => PermissionEnum::QL_CAI_DAT->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_CAI_DAT_CHI_TIET->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_CAI_DAT_THEM_MOI->value,
                'NAME' => PermissionEnum::QL_CAI_DAT_THEM_MOI->description(),
                'PARENT_CODE' => PermissionEnum::QL_CAI_DAT->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_CAI_DAT_THEM_MOI->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_CAI_DAT_CHINH_SUA->value,
                'NAME' => PermissionEnum::QL_CAI_DAT_CHINH_SUA->description(),
                'PARENT_CODE' => PermissionEnum::QL_CAI_DAT->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_CAI_DAT_CHINH_SUA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'CODE' => PermissionEnum::QL_CAI_DAT_XOA->value,
                'NAME' => PermissionEnum::QL_CAI_DAT_XOA->description(),
                'PARENT_CODE' => PermissionEnum::QL_CAI_DAT->value,
                'TREE_LEVEL' => 2,
                'DESCRIPTION' => PermissionEnum::QL_CAI_DAT_XOA->description(),
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

        ];

        foreach ($arrPermission as $index => $permission) {
            $exists = DB::table('permission')->where([
                ['CODE', '=', $permission['CODE']]
            ])->exists();

            if (!$exists) {
                DB::table('permission')->insert($permission);
            } else {
                DB::table('permission')->where([
                    ['CODE', '=', $permission['CODE']]
                ])->update($permission);
            }
        }
    }
}
