<?php

namespace Database\Seeders;

use App\Enum\AppConstant;
use App\Enum\AuthConstant;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $arrRolePermission = [
            /* ADMIN */
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_NGUOI_DUNG',
                'DESCRIPTION' => 'Quyền truy cập menu Người dùng',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_NGUOI_DUNG_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Người dùng',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_NGUOI_DUNG_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Người dùng',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_NGUOI_DUNG_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Người dùng',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_NGUOI_DUNG_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Người dùng',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_NGUOI_DUNG_XOA',
                'DESCRIPTION' => 'Quyền xóa Người dùng',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_SAN_PHAM',
                'DESCRIPTION' => 'Quyền truy cập menu Danh mục sản phẩm',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_SAN_PHAM_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Danh mục sản phẩm',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_SAN_PHAM_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Danh mục sản phẩm',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_SAN_PHAM_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Danh mục sản phẩm',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_SAN_PHAM_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Danh mục sản phẩm',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_SAN_PHAM_XOA',
                'DESCRIPTION' => 'Quyền xóa Danh mục sản phẩm',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_SAN_PHAM',
                'DESCRIPTION' => 'Quyền truy cập menu Sản phẩm',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_SAN_PHAM_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Sản phẩm',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_SAN_PHAM_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Sản phẩm',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_SAN_PHAM_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Sản phẩm',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_SAN_PHAM_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Sản phẩm',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_SAN_PHAM_XOA',
                'DESCRIPTION' => 'Quyền xóa Sản phẩm',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_TIN_TUC',
                'DESCRIPTION' => 'Quyền truy cập menu Tin tức',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_TIN_TUC_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Tin tức',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_TIN_TUC_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Tin tức',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_TIN_TUC_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Tin tức',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_TIN_TUC_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Tin tức',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_TIN_TUC_XOA',
                'DESCRIPTION' => 'Quyền xóa Tin tức',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_TIN_TUC',
                'DESCRIPTION' => 'Quyền truy cập menu Danh mục tin tức',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_TIN_TUC_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Danh mục tin tức',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_TIN_TUC_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Danh mục tin tức',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_TIN_TUC_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Danh mục tin tức',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_TIN_TUC_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Danh mục tin tức',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_TIN_TUC_XOA',
                'DESCRIPTION' => 'Quyền xóa Danh mục tin tức',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET',
                'DESCRIPTION' => 'Quyền truy cập menu Danh mục bài viết',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Danh mục bài viết',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Danh mục bài viết',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Danh mục bài viết',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Danh mục bài viết',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET_XOA',
                'DESCRIPTION' => 'Quyền xóa Danh mục bài viết',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_BAI_VIET',
                'DESCRIPTION' => 'Quyền truy cập menu Bài viết',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_BAI_VIET_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Bài viết',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_BAI_VIET_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Bài viết',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_BAI_VIET_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Bài viết',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_BAI_VIET_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Bài viết',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_BAI_VIET_XOA',
                'DESCRIPTION' => 'Quyền xóa Bài viết',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_VIDEO',
                'DESCRIPTION' => 'Quyền truy cập menu Video',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_VIDEO_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Video',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_VIDEO_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Video',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_VIDEO_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Video',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_VIDEO_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Video',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_VIDEO_XOA',
                'DESCRIPTION' => 'Quyền xóa Video',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_VIDEO_XEM',
                'DESCRIPTION' => 'Quyền xem Video',
                'SORT_ORDER' => 7,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_THONG_TIN_CA_NHAN',
                'DESCRIPTION' => 'Quyền truy cập menu Thông tin cá nhân',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_THONG_TIN_CA_NHAN_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Thông tin cá nhân',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_THONG_TIN_CA_NHAN_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Thông tin cá nhân',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_CAI_DAT',
                'DESCRIPTION' => 'Quyền truy cập menu Cài đặt',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_CAI_DAT_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Cài đặt',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_CAI_DAT_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Cài đặt',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_CAI_DAT_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Cài đặt',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_CAI_DAT_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Cài đặt',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 1,
                'PERMISSION_CODE' => 'QL_CAI_DAT_XOA',
                'DESCRIPTION' => 'Quyền xóa Cài đặt',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            
            /* CHUYEN_VIEN */
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_SAN_PHAM',
                'DESCRIPTION' => 'Quyền truy cập menu Sản phẩm',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_SAN_PHAM_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Sản phẩm',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_SAN_PHAM_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Sản phẩm',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_SAN_PHAM_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Sản phẩm',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_SAN_PHAM_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Sản phẩm',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_SAN_PHAM_XOA',
                'DESCRIPTION' => 'Quyền xóa Sản phẩm',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_TIN_TUC',
                'DESCRIPTION' => 'Quyền truy cập menu Tin tức',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_TIN_TUC_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Tin tức',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_TIN_TUC_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Tin tức',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_TIN_TUC_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Tin tức',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_TIN_TUC_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Tin tức',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_TIN_TUC_XOA',
                'DESCRIPTION' => 'Quyền xóa Tin tức',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET',
                'DESCRIPTION' => 'Quyền truy cập menu Danh mục bài viết',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Danh mục bài viết',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Danh mục bài viết',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Danh mục bài viết',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Danh mục bài viết',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_DANH_MUC_BAI_VIET_XOA',
                'DESCRIPTION' => 'Quyền xóa Danh mục bài viết',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_BAI_VIET',
                'DESCRIPTION' => 'Quyền truy cập menu Bài viết',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_BAI_VIET_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Bài viết',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_BAI_VIET_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Bài viết',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_BAI_VIET_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Bài viết',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_BAI_VIET_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Bài viết',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_BAI_VIET_XOA',
                'DESCRIPTION' => 'Quyền xóa Bài viết',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_DANH_MUC_SAN_PHAM_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Danh mục sản phẩm',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_VIDEO',
                'DESCRIPTION' => 'Quyền truy cập menu Video',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_VIDEO_DANH_SACH',
                'DESCRIPTION' => 'Quyền xem danh sách Video',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_VIDEO_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Video',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_VIDEO_THEM_MOI',
                'DESCRIPTION' => 'Quyền thêm mới Video',
                'SORT_ORDER' => 4,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_VIDEO_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Video',
                'SORT_ORDER' => 5,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_VIDEO_XOA',
                'DESCRIPTION' => 'Quyền xóa Video',
                'SORT_ORDER' => 6,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_VIDEO_XEM',
                'DESCRIPTION' => 'Quyền xem Video',
                'SORT_ORDER' => 7,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],

            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_THONG_TIN_CA_NHAN',
                'DESCRIPTION' => 'Quyền truy cập menu Thông tin cá nhân',
                'SORT_ORDER' => 1,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_THONG_TIN_CA_NHAN_CHI_TIET',
                'DESCRIPTION' => 'Quyền xem chi tiết Thông tin cá nhân',
                'SORT_ORDER' => 2,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ],
            [
                'ROLE_ID' => 2,
                'PERMISSION_CODE' => 'QL_THONG_TIN_CA_NHAN_CHINH_SUA',
                'DESCRIPTION' => 'Quyền chỉnh sửa Thông tin cá nhân',
                'SORT_ORDER' => 3,
                'CRT_DT' => now(),
                'UPD_DT' => now(),
                'CRT_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'UPD_ID' => AuthConstant::USER_SUPER_ADMIN_ID,
                'CRT_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'UPD_NAME' => AuthConstant::USER_SUPER_ADMIN_FULL_NAME,
                'STATUS' => AppConstant::STATUS_USING,
                'IS_ACTIVE' => true
            ]
        ];

        foreach ($arrRolePermission as $index => $rolePermission) {
            $exists = DB::table('role_permission')->where([
                ['ROLE_ID', '=', $rolePermission['ROLE_ID']],
                ['PERMISSION_CODE', '=', $rolePermission['PERMISSION_CODE']]
            ])->exists();

            if (!$exists) {
                DB::table('role_permission')->insert($rolePermission);
            } else {
                DB::table('role_permission')->where([
                    ['ROLE_ID', '=', $rolePermission['ROLE_ID']],
                    ['PERMISSION_CODE', '=', $rolePermission['PERMISSION_CODE']]
                ])->update($rolePermission);
            }
        }
    }
}
